language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.9
branches:
only:
    - dev
    - master
before_script:
    - npm install -g istanbul
    - npm install -g mocha
after_success:
    - make test-cov
    - make coveralls